{{ if or .VAlues.global.istio.enabled .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - "*"
  gateways:
  - bluecompute-web-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-web.default.svc.cluster.local
        port:
          number: 80
{{ end }}