apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - "*"
  gateways:
  - web-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-web.default.svc.cluster.local
        port:
          number: 80
  # tls:
  # - match:
  #   - sniHosts:
  #     - "*"
  #   route:
  #   - destination:
  #       host: release-name-web
  #       port:
  #         number: 80
